Article: Controlling the familywise error rate when performing
multiple comparisons in a Linear Latent Variable Model

Authors: Brice Ozenne, Esben Budtz-J\o{}rgensen, Sebastian Elgaard Ebert.

Author responsible for writing the code: Brice Ozenne.

E-mail of the author maintaining the code: brice.ozenne@nru.dk

* Content of the folder
The file describes the infra structure of the simulations studies of
the manuscript. This infrastructure is composed of the following
files/folders:
- [[./SUBM]] runs the simulations defined in the [[./BATCH]] files and export
  the results in the [[./Results]] folder (in .rds format, not uploaded on
  Github due to space restriction).
- [[./BUILD.R]] process the results and export them in the [[./Results]] folder.
  [[./figure3.R]], [[./figure4.R]], [[./figure5.R]]
- [[./figure2.R]], [[./figure3.R]], [[./figure4.R]], [[./figure5.R]]: R code used to
  generate figure 2, 3, 4, and 5 of the article. 
- [[./table1.R]] and [[./table2.R]]: R code used to generate table 1 and 2 of
  the article. Note that since we are not allowed to share the actual
  data, simulated are used instead which may lead to numerical
  differences between the R output and the content of the article.
- [[./postSelection.R]]: R code used to obtain the results in section 5.3.
- [[./analysis.R]]: R code used in the illustration section.
- [[./type1-smith2013.R]]: example where the FWER is not correctly
  controled using the modified Bonferroni procedure of Smith and
  Cribbie (2013).
- [[./Figures]] figures used in the article and created by [[./figure2.R]],
- [[./Software]] package lavaSearch2 used to run the simulations.
